import json,re,subprocess,sys
data=json.load(open('node_modules/next/dist/compiled/@next/font/dist/google/font-data.json'))
GROUPS={
"common":["Inter","Roboto","Open Sans","Lato","Montserrat","Poppins","Nunito","Nunito Sans","Raleway","Work Sans","DM Sans","Rubik","Karla","Mulish","Cabin","Ubuntu","Source Sans 3","Fira Sans","PT Sans","Noto Sans","Public Sans","IBM Plex Sans","Figtree","Outfit","Sora","Manrope","Plus Jakarta Sans","Lexend","Urbanist","Jost","Josefin Sans","Archivo","Barlow","Hind","Dosis","Signika","Sen","Quicksand","Varela Round","Heebo","Assistant","Titillium Web","Exo 2","Kanit","Prompt","Red Hat Display","Red Hat Text","Onest","Instrument Sans","Geist"],
"geometric":["Syne","Unbounded","Bricolage Grotesque","Familjen Grotesk","Gabarito","Funnel Display","Host Grotesk","Schibsted Grotesk","Golos Text","Hanken Grotesk","Albert Sans","Epilogue","Kumbh Sans","Sofia Sans","Wix Madefor Display","Rethink Sans","Afacad","Reddit Sans","Parkinsans","Darker Grotesque","Space Grotesk","League Spartan","Questrial","Poppins","Montserrat Alternates","Comfortaa","Fredoka","Baloo 2","Lexend Zetta","Lexend Mega","Lexend Exa","Lexend Giga","Tilt Warp","Tilt Neon","Anta","Bruno Ace","Bruno Ace SC","Tomorrow","Tektur","Kdam Thmor Pro","Genos","Trispace","Smooch Sans","Mohave","Pathway Extreme","Spinnaker","Telex","Voltaire","Yantramanav","M PLUS Rounded 1c","Zen Kaku Gothic New","Dela Gothic One"],
"retro":["Righteous","Audiowide","Days One","Monomaniac One","Concert One","Lilita One","Paytone One","Bowlby One","Bowlby One SC","Racing Sans One","Krona One","Goldman","Iceberg","Turret Road","Sarpanch","Fugaz One","Chango","Contrail One","Boogaloo","Sansita","Sniglet","Shrikhand","Titan One","Rowdies","Bagel Fat One","Gasoek One","Bangers","Luckiest Guy","Alfa Slab One","Ultra","Rammetto One","Rubik Mono One","Black Ops One","Bungee","Passion One","Squada One","Russo One","Poller One","Jockey One","Marvel","Homenaje","Geo","Rationale","Strait","Economica","Share","Share Tech","Limelight","Poiret One","Abril Fatface","Yeseva One","Lobster","Pacifico","Kaushan Script","Permanent Marker","Protest Strike","Protest Riot","Chonburi","Cherry Bomb One","Mochiy Pop One","Jaro","Climate Crisis","Foldit","Faster One","Wallpoet","Syncopate","Major Mono Display","Bungee Shade","Bungee Inline","Monoton"],
"space":["Orbitron","Michroma","Chakra Petch","Oxanium","Quantico","Aldrich","Electrolize","Jura","Nova Square","Nova Flat","Nova Round","Play","Saira","Rajdhani","Bai Jamjuree","Advent Pro","Gruppo","Stick No Bills","Sono","Exo","Zen Dots","Tourney","Krub","Mitr","Niramit","Grandstander"],
"serif":["Playfair Display","Merriweather","Lora","Roboto Slab","Bitter","Zilla Slab","Arvo","Libre Baskerville","DM Serif Display","Fraunces","Instrument Serif","Young Serif","Newsreader","Spectral","Crimson Pro","EB Garamond","Cardo","Alegreya","Bodoni Moda","Italiana","Marcellus","Forum","Julius Sans One","Cinzel","Cinzel Decorative","Cormorant Garamond","Josefin Slab","Noto Serif","Source Serif 4","Domine","Vollkorn","Prata","Gloock","Bevan"],
"condensed":["Oswald","Bebas Neue","Anton","Anton SC","Antonio","Teko","Archivo Black","Archivo Narrow","Barlow Condensed","Barlow Semi Condensed","Saira Condensed","Sofia Sans Condensed","Fjalla One","Pathway Gothic One","League Gothic","Big Shoulders Text","Roboto Condensed","Open Sans Condensed","Fira Sans Condensed","Ubuntu Condensed","Encode Sans Condensed","Yanone Kaffeesatz","Khand","Pragati Narrow","Six Caps","Staatliches","Bungee Hairline"],
"mono":["Space Mono","JetBrains Mono","Geist Mono","Martian Mono","IBM Plex Mono","Roboto Mono","Fira Code","Source Code Pro","DM Mono","Azeret Mono","Sometype Mono","Red Hat Mono","Chivo Mono","Spline Sans Mono","Nova Mono","Share Tech Mono","Major Mono Display","Xanh Mono","Kode Mono","Ubuntu Mono","Courier Prime","Inconsolata","Overpass Mono","Cutive Mono","Syne Mono","Fragment Mono","B612 Mono"],
"futuristic":["Bruno Ace","Bruno Ace SC","Anta","Tektur","Unica One","Federo","Megrim","Kenia","Revalia","Stalinist One","Bungee Outline","Rubik Iso","Rubik 80s Fade","Rubik Vinyl","Rubik Moonrocks","Rubik Lines","Rubik Glitch","Rubik Maze","Genos","Tomorrow","Trispace","Kdam Thmor Pro","Saira Stencil One","Allerta Stencil","Stardos Stencil","Sirin Stencil","Emblema One","Big Shoulders Stencil Display","Big Shoulders Inline Display","Codystar","Ropa Sans","Prosto One","Kelly Slab","Sansation","Michroma","Audiowide","Orbitron","Zen Dots","Tourney","Syncopate","Iceland","Wallpoet","Faster One","Monoton","Nova Oval","Nova Cut","Nova Script","Nova Slim","Lexend Zetta","Lexend Mega","Jaro","Foldit","Climate Crisis","Rubik Mono One","Rubik Lines"],
"script":["Pacifico","Lobster","Lobster Two","Kaushan Script","Dancing Script","Great Vibes","Satisfy","Cookie","Courgette","Sacramento","Yellowtail","Allura","Alex Brush","Parisienne","Tangerine","Pinyon Script","Mr Dafoe","Norican","Oleo Script","Oleo Script Swash Caps","Sansita Swashed","Berkshire Swash","Playball","Damion","Marck Script","Caveat","Shadows Into Light","Indie Flower","Amatic SC","Permanent Marker","Rock Salt","Homemade Apple","Nothing You Could Do","Reenie Beanie","Covered By Your Grace","Gloria Hallelujah","Architects Daughter","Patrick Hand","Kalam","Handlee","Neucha","Comic Neue","Bad Script","Merienda","Niconne","Rochester","Rouge Script","Herr Von Muellerhoff","Monsieur La Doulaise","Mrs Saint Delafield","Italianno","Grand Hotel","Lily Script One","Leckerli One","Style Script","Cherish","Carattere","Caramel","Ephesis","Ms Madi","Send Flowers","Splash","Water Brush","Whisper","Ballet","Birthstone","Bonheur Royale","Corinthia","Estonia","Hurricane","Imperial Script","Inspiration","Island Moments","Kolker Brush","Lavishly Yours","Love Light","Luxurious Script","Meow Script","Moon Dance","Mea Culpa","Neonderthaw","Oooh Baby","Passions Conflict","Petemoss","Puppies Play","Qwitcher Grypen","Sassy Frass","Smooch","Square Peg","Tapestry","The Nautigal","Twinkle Star","Updock","Vujahday Script","Waterfall","Comforter","Comforter Brush","Explora","Festive","Gwendolyn","Licorice","Mrs Sheppards","My Soul","Praise","Babylonica","Beau Rivage","Fuggles","Charm","Charmonman","Mali","Itim","Sriracha","Pattaya","Sofia","Euphoria Script","Clicker Script","Engagement","Kristi","La Belle Aurore","Meddon","Over the Rainbow","Sue Ellen Francisco","Zeyada","Cedarville Cursive","Dawning of a New Day","Give You Glory","Just Me Again Down Here","Loved by the King","Waiting for the Sunrise","Calligraffitti","Coming Soon","Crafty Girls","Delius","Delius Swash Caps","Gochi Hand","Just Another Hand","Schoolbell","Short Stack","Sunshiney","Swanky and Moo Moo","Walter Turncoat","Annie Use Your Telescope","Chilanka","Gaegu","Nanum Pen Script","Nanum Brush Script","Hi Melody","Dokdo","East Sea Dokdo","Gamja Flower","Poor Story","Single Day","Stylish","Yeon Sung","Cute Font","Do Hyeon","Jua","Kirang Haerang","Black Han Sans","Black And White Picture","Song Myung","Gugi","Sunflower","Hahmlet","Gowun Dodum","Gowun Batang","Nanum Gothic","Nanum Myeongjo","Noto Sans KR"],
"display":["Rye","Vast Shadow","Chewy","Ranchers","Londrina Solid","Londrina Shadow","Londrina Outline","Londrina Sketch","Fredericka the Great","Modak","Kavoon","Lemon","Cherry Cream Soda","Frijole","Knewave","Original Surfer","Sonsie One","Spicy Rice","Ribeye","Ribeye Marrow","Sedgwick Ave","Sedgwick Ave Display","Slackey","Trade Winds","Freckle Face","Fontdiner Swanky","Henny Penny","Nixie One","Elsie","Mystery Quest","Bevan","Ultra","Alfa Slab One","Bowlby One","Bangers","Luckiest Guy","Titan One","Rowdies","Bagel Fat One","Gasoek One","Chango","Boogaloo","Sniglet","Shrikhand","Abril Fatface","Yeseva One","Limelight","Poiret One","Chonburi","Cherry Bomb One","Mochiy Pop One","Bungee Shade","Bungee Inline","Bungee Hairline","Black Ops One","Squada One","Poller One","Jockey One","Marvel","Homenaje","Geo","Rationale","Strait","Economica","Share","Share Tech","Protest Strike","Protest Riot","Protest Revolution","Protest Guerrilla","Passion One","Paytone One","Lilita One","Concert One","Days One","Monomaniac One","Racing Sans One","Krona One","Goldman","Turret Road","Sarpanch","Fugaz One","Contrail One","Sansita","Righteous","Anton","Archivo Black","Bebas Neue","Teko","Oswald","Fjalla One","Staatliches","Six Caps","Big Shoulders Display","Alumni Sans","Alumni Sans Collegiate One","Alumni Sans Inline One","Alumni Sans Pinstripe","Graduate","Carter One","Coda","Coiny","Fascinate","Fascinate Inline","Faster One","Flavors","Galindo","Gorditas","Hanalei","Hanalei Fill","Joti One","Kumar One","Kumar One Outline","Lakki Reddy","Margarine","Metal Mania","Miltonian","Miltonian Tattoo","Moul","Mouse Memoirs","New Rocker","Nosifer","Piedra","Pirata One","Sancreek","Sarina","Shojumaru","Smokum","Snowburst One","Stint Ultra Expanded","Stint Ultra Condensed","Supermercado One","Trochut","Unkempt","Wendy One","Zilla Slab Highlight","Bungee","Dela Gothic One","Reggae One","RocknRoll One","Rampart One","Stick","Train One","Yusei Magic","Kaisei Opti","Kaisei Decol","Kaisei HarunoUmi","Kaisei Tokumin","Potta One","Hachi Maru Pop","Yomogi","Zen Antique","Zen Kurenaido","Zen Loop","Zen Maru Gothic","Zen Old Mincho","Klee One","Shippori Antique","Shippori Antique B1","Mochiy Pop P One","Murecho","M PLUS 1","M PLUS 2","M PLUS 1 Code","BIZ UDPGothic","BIZ UDPMincho","Kosugi","Kosugi Maru","Sawarabi Gothic","Sawarabi Mincho","Hina Mincho","Yuji Boku","Yuji Mai","Yuji Syuku","Yuji Hentaigana Akari","Yuji Hentaigana Akebono","Rubik Iso"],
}
seen=set(); missing=[]; entries=[]
for g,names in GROUPS.items():
    for n in names:
        if n in seen: continue
        f=data.get(n)
        if not f or 'latin' not in f['subsets'] or 'korean' in f['subsets'] or 'japanese' in f['subsets']: missing.append(n); continue
        seen.add(n)
        ident=n.replace(' ','_')
        var=re.sub(r'[^a-zA-Z0-9]','',n); var=var[0].lower()+var[1:]
        if var[0].isdigit(): var='f'+var
        ws=[w for w in f['weights'] if w!='variable' and w.isdigit()]
        if 'variable' in f['weights']: opt='{ subsets: ["latin"] }'
        else:
            ws=[w for w in ws if 400<=int(w)<=900] or ws
            opt='{ subsets: ["latin"], weight: '+json.dumps(ws if len(ws)>1 else ws[0])+' }'
        entries.append((g,n,ident,var,opt))
print("missing:",missing,file=sys.stderr); print(len(entries),file=sys.stderr)
imports=", ".join(e[2] for e in entries)
loaders="\n".join(f'const {e[3]} = {e[2]}({e[4]});' for e in entries)
rows="\n".join(f'  {{ name: "{e[1]}", family: {e[3]}.style.fontFamily, group: "{e[0]}" }},' for e in entries)
open('/private/tmp/claude-501/-Users-dpusateri-code-hypertheory-hypertheory/d432792b-6fe4-4a24-9669-45457b45bd55/scratchpad/fontblock.txt','w').write(f"import {{\n  {imports},\n}} from \"next/font/google\";\n\n{loaders}\n\nconst FONTS: {{ name: string; family: string | null; group: Group }}[] = [\n  {{ name: \"Current (Figtree)\", family: null, group: \"common\" }},\n{rows}\n];\n")
